CREATE OR REPLACE FUNCTION CalculateAge (
  cust_id IN NUMBER
) RETURN NUMBER
IS
  age NUMBER;
  dob DATE;
BEGIN
  SELECT DOB INTO dob FROM Customers WHERE CustomerID = cust_id;
  age := FLOOR(MONTHS_BETWEEN(SYSDATE, dob) / 12);
  RETURN age;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL; 
  WHEN OTHERS THEN
    RETURN NULL; 
END;
/
